fail_fast: true
default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-case-conflict
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-illegal-windows-names
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: detect-private-key
      - id: debug-statements
      - id: forbid-submodules
      - id: check-added-large-files
        args: ["--maxkb=900", "--enforce-all"]
        exclude: ""

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: Format code

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.11"
    hooks:
      - id: ruff
        args: [ "--fix" ]

  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.15.0
    hooks:
     - id: reorder-python-imports
       args: [--py38-plus]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        name: mypy
        entry: mypy .
        pass_filenames: false
        additional_dependencies:
          - types-requests
          - types-redis

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: [ --py311-plus ]
        name: Upgrade code

  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
        name: Unused noqa
        additional_dependencies:
          #- pep8-naming
          - flake8-pytest-style
          - flake8-bandit
          - flake8-simplify
          - flake8-return

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        args: [ --line-length=120 ]

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          #- mdformat-black
          - mdformat_frontmatter

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        stages: [pre-commit]
        types: [python]
        entry: uv run pytest -x
        language: system
        pass_filenames: false
